apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-configmap
data:
  tenant: {{ .Values.tenant }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-deployment
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ .Release.Name }}-pod
  template:
    metadata:
      name: {{ .Release.Name }}-pod
      labels:
        app.kubernetes.io/name: {{ .Release.Name }}-pod
    spec:
      containers:
      - name: helloenv
        image: helloenv:1.0.0
        ports:
        - containerPort: 8080
        env:
        - name: HELLOENV_TENANT
          valueFrom:
            configMapKeyRef:
              name: {{ .Release.Name }}-configmap
              key: tenant
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-autoscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-deployment
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 75
  # metrics:
  # - type: Resource
  #   resource:
  #     name: cpu
  #     target:
  #       type: Utilization
  #       avarageUtilization: 75
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-service
spec:
  selector:
    app.kubernetes.io/name: {{ .Release.Name }}-pod
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
  - host: "kubernetes.docker.internal"
    http:
      paths:
      - path: /s/{{ .Values.tenant }}
        pathType: Prefix
        backend:
          service:
            name: {{ .Release.Name }}-service
            port:
              number: 80